### ISSUE TITLE
HMS-RC suggests using transfer server instead of transfer partition

### ISSUE THREAD

**Issue by hywu0110** [bioinfonerd/CyCif_Manager#19]
The first part when using this pipeline is to move files. The default approach is to use the transfer partition by submitting a slurm job to "transfer". I asked HMS-RC for access and they suggested me to use the transfer server instead. This means I'll need to ssh into the transfer server, "nohup rsync [source file] [destination file]", and then logout and wait for it to finish. The HMS-RC believes this is more efficient because "There are only a couple of very low-memory compute nodes accessible through that partition, so jobs there will most likely run slower than the transfer servers, and potentially take time to even dispatch if others are using those nodes."

It's very minor but maybe we can let users know that they will be responsible for moving files.

**Comment by bioinfonerd** [comment]
Difficulty with their suggestion is the lack of access to slurm from the transfer partition.  Ideally, it would be nice for a user (at least if it was me) to let the pipeline handle the transferring of data.  So the workflow would be, tell the pipeline to run and it handles transferring, running, and uploading to Omero automatically.  Using the transfer que is the only solution to do that at the moment because of how HMS-RC has set it up.
